name: IPFS (single node)
description: |
  A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
version: v1.0.0
category: Applications
maintainer: growingabit
license: AGPL-3.0
projectURL: https://ipfs.io/